### ISSUE TITLE
random panic if client disconnects non gracefully

### ISSUE THREAD

**Issue by stepan-romankov** [gbaranski/ezsockets#10]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: SendError

[session.rs:99:33](https://github.com/gbaranski/ezsockets/blob/master/src/session.rs#L99)
```rust
    /// Calls a method on the session
    pub async fn call(&self, params: P) {
        self.calls.send(params).unwrap();
    }
````
I assume that .unwrap()'s in many places can cause panics which makes websocket server not able to handle further connections.

**Comment by gbaranski** [comment]
Okay I see what's the problem, you mustn't use `SessionExt::call` method after Session is closed.

First, I replaced the unwrap with more meaningful errors.

And here we have few solutions to the problem.
1. Add `alive()` method on `Session`, to check whether the Session is still alive, before calling anything. 
https://github.com/gbaranski/ezsockets/blob/d557c68c340faa5f0d6eac14955c9d60b580dc4d/src/session.rs#L87-L90

2. Move all tasks handles which refer to the Session handle inside of `Session: SessionExt` itself, so you can implement `core::ops::Drop` manually, and abort the tasks.
https://github.com/gbaranski/ezsockets/blob/e3963b6ecc92de80cac7c5e13058e15db79b40d3/examples/counter-server/src/main.rs#L72-L76

3. Make use of `Server::disconnect`.
