### ISSUE TITLE
Connection callbacks

### ISSUE THREAD

**Issue by blahbleepew** [gbaranski/ezsockets#17]
I need to respond to connection drops on the client, can you add reconnect() and close() callback handlers to ClientExt? I could make a PR if you're busy.

**Comment by gbaranski** [comment]
I'll work on that on #18

Are you sure if `reconnect()` is needed, if you have `closed()`, you can simply add something like
```rust
#[async_trait]
impl ezsockets::ClientExt for MyClient {
    // ...

    async fn closed(&mut self) -> Result<(), ezsockets::Error> {
        tokio::time::sleep(ezsockets::DEFAULT_RECONNECT_INTERVAL).await;
        // Now it should be basically at the same moment as the `reconnect()` you've suggested
        Ok(())
    }
}
```

**Comment by gbaranski** [comment]
And if you specifically want to handle connections, there'll be also function `connected()` added on the same PR.

**Comment by blahbleepew** [comment]
This looks very nice, thank you!
