### ISSUE TITLE
unwrap()s

### ISSUE THREAD

**Issue by berkus** [gbaranski/ezsockets#20]
https://github.com/gbaranski/ezsockets/blob/99534d11f0248e29bd61e1c175b9306cb17bb3fc/src/client.rs#L148

Are these sends always succeeding and are fine to be unwrapped?

**Comment by gbaranski** [comment]
Yep, they should succeed, because `Err` will be returned from `.send()` only in case when the `mpsc::UnboundedReceiver` is dropped, and it should never be.

But if you encounter a situation where this `Err` is returned, please open a new issue :)
