### ISSUE TITLE
Connect request customizability

### ISSUE THREAD

**Issue by ljoonal** [gbaranski/ezsockets#23]
In my use case of communicating to a game server's WS API, an additional authentication header is required in the initial HTTP connection, which can be achieved [with `tokio_tungstenite` for example](https://github.com/onlivfe/chilloutvr_rs/blob/865133c4cca63a72239af7120a431d15a0b280b2/src/api_client/ws.rs#L65).

[`ezsockets::client::ClientConfig`](https://docs.rs/ezsockets/latest/ezsockets/client/struct.ClientConfig.html#) however currently seems to be limited to only being able to add a basic auth header..?
I'm curious if there's a reason for [not exposing the headers](https://github.com/gbaranski/ezsockets/blob/012066f91c45e1835be5b10b0c86af06a04c6156/src/client.rs#L73) & only allowing addition of basic auth?

**Comment by gbaranski** [comment]
You're completely right, I somehow missed this feature.
I'll add this in a moment.

**Comment by gbaranski** [comment]
done :)
if anything else you think is needed, please open a new issue.
