### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by satvikpendem** [gbaranski/ezsockets#26]

**Comment by gbaranski** [comment]
Where exactly? On Github releases I'm adding information about what has been changed with each release, e.g for v0.4.3 https://github.com/gbaranski/ezsockets/releases/tag/v0.4.3

**Comment by satvikpendem** [comment]
Ah ok I didn't see that. Usually I look for a CHANGELOG.md file in the repo to figure out what changed between each version. Reading commit messages is arguably also not a great experience for the user.

**Comment by gbaranski** [comment]
closed by a624574
