### ISSUE TITLE
get_args is useless

### ISSUE THREAD

**Issue by qiujiangkun** [gbaranski/ezsockets#35]
run_on() takes  `get_args: impl Fn(&mut Socket) -> GetArgsFut`, but Socket is just a pair of channels. It's not possible to do anything useful with get_args, even in demos

**Comment by gbaranski** [comment]
maybe instead of Args we could just pass `http::Request` to `Server::accept()`?

**Comment by qiujiangkun** [comment]
Yes it's a better idea
