### ISSUE TITLE
Handle custom behaviour when disconnected

### ISSUE THREAD

**Issue by kevinheavey** [gbaranski/ezsockets#48]
When my client gets disconnected, I'd like to do some custom action (like print a warning) as well as attempting to reconnect. Right now the only thing I can customize is how long it waits to reconnect, right?

**Comment by kevinheavey** [comment]
Oh wait on_close() always gets called when disconnected, right? So I can just use that

**Comment by gbaranski** [comment]
> Oh wait on_close() always gets called when disconnected, right? So I can just use that

Yep, you can just use that. I'll try to clarify that in the docs.
