### ISSUE TITLE
Early returning from on_connect results in panic

### ISSUE THREAD

**Issue by RoeeJ** [gbaranski/ezsockets#51]
Hi there, great work on this crate
I'm using an on_connect implementation such as the following to have the server kill a connection if it doesn't pass some checks (specifically, using axum to extract headers and validate data passed within them)
```
async fn on_connect(&mut self, socket: Socket, address: SocketAddr, args: <Self::Session as SessionExt>::Args) -> Result<ezsockets::Session<<Self::Session as SessionExt>::ID, <Self::Session as SessionExt>::Call>, Error> {
        info!("New connection from {}, {:?}", &address, &args);
        return Err(anyhow!("Not implemented!").into());
}
```

which results in the following panic (removed full backtrace, will attach if relevant)
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/roee/.cargo/registry/src/github.com-1ecc6299db9ec823/ezsockets-0.5.1/src/server.rs:248:14
```

which leads me to the following snippet in server.rs
```
pub async fn accept(
        &self,
        socket: Socket,
        address: SocketAddr,
        args: <E::Session as SessionExt>::Args,
    ) -> <E::Session as SessionExt>::ID {
        let (sender, receiver) = oneshot::channel();
        self.connections
            .send(NewConnection {
                socket,
                address,
                args,
                respond_to: sender,
            })
            .map_err(|_| ())
            .unwrap();
        receiver.await.unwrap()
    }
```
A potential solution would be to eliminate the unwrap from both expressions, or modify the return type of the 'accept' function to an enumeration that includes either a session or an exit code.

**Comment by gbaranski** [comment]
Hey,
if you want to make some checks on HTTP headers, it's best to do it in your own `axum` HTTP handler, instead of in the `ServerExt::on_connect` implementation.
I made an example of this, check it out here
https://github.com/gbaranski/ezsockets/blob/master/examples/chat-server-axum/src/main.rs#L139-L154
