### ISSUE TITLE
Race conditions

### ISSUE THREAD

**Issue by UkoeHB** [gbaranski/ezsockets#53]
The calls to `.unwrap()` in the client, server, and session APIs all race with the dropping of the corresponding actors. In the session code, for example, you have `PANIC_MESSAGE_UNHANDLED_CLOSE`, but it is not possible to race-free test liveness before invoking one of those methods without some kind of lock (which would be hard to implement). Instead, I recommend returning Results from all of those methods. Websocket servers and clients should never panic, because that is an attack vector for DOS.

EDiT: this problem is exacerbated by the inability to call `std::panic::catch_unwind()` on any of the objects in this crate, since they are not 'unwind safe'.

**Comment by gbaranski** [comment]
Hmm, I did it without Result just to simplify the usage. Will work on this.
