### ISSUE TITLE
Reject connections before accepting them

### ISSUE THREAD

**Issue by UkoeHB** [gbaranski/ezsockets#72]
Currently you can only reject a connection after the websockets backend has accepted the connection. This means clients will always see 'connected' -> 'disconnected' events even if their connection request was rejected by your custom `ServerExt`.

There should be an additional step in the connection-acceptance protocol for pre-validating requests before the websockets backend can accept the connection.

It should be possible to move that step into the axum `Upgrade::from_request()` method and tungstenite `Acceptor .. callback` closure, although it's not clear the optimal/correct approach since server actors are async from their servers (there is a risk of introducing race conditions between pre-validating requests and registering connections in the `ServerExt`, e.g. if you reject duplicate connections).

**Comment by gbaranski** [comment]
In Axum there's a way - take a look at this example:
https://github.com/gbaranski/ezsockets/blob/52c4b7898e537a1acb179503a89e5612ecd730f4/examples/chat-server-axum/src/main.rs#L150-L158

You can do some work before calling `ezsocket.on_upgrade(server)`.

**Comment by gbaranski** [comment]
Yes that's true. 
I think `ezsockets` had this feature in one of its prior version, not sure though.
We can implement this feature, but I'd prefer to make it exclusive to `tungstenite` runtime, so that it doesn't affect `axum` and doesn't make two ways to do rejection before accept.
