### ISSUE TITLE
Ping/Pong are unavailable in browser

### ISSUE THREAD

**Issue by UkoeHB** [gbaranski/ezsockets#76]
Ping/Pong are [not available](https://stackoverflow.com/questions/10585355/sending-websocket-ping-pong-frame-from-browser) in all browsers, and if they are it always happens in the background. The canonical [`web_sys::WebSocket`](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebSocket.html#method.onclose) implementation offers no Ping/Pong functionality.

This is a problem because I want to enable browser-based websocket clients in ezsockets (e.g. [this](https://docs.rs/ws_stream_wasm/0.7.4/ws_stream_wasm/index.html) is the best contender), but ezsockets depends on `Ping/Pong` for the heartbeat. (I want to abstract out the client's `tokio_tungstenite::connect_async()` call.)

To get around this, I want to:
A) Move the `Socket`'s `last_alive` to always update when receiving a message, instead of only when receiving a Pong.
B) In my downstream project, use `Message::Text` to manually implement a Ping/Pong keep-alive when compiling to WASM.
C) Disable the keep-alive mechanism entirely when compiling to WASM (do this in addition to A, since servers won't compile to WASM and still need the keep-alive mechanism).

Alternatively, we could inject the keep-alive Ping/Pong into `Message::Text` in ezsockets (pretty invasive).

**Comment by gbaranski** [comment]
> A) Move the Socket's last_alive to always update when receiving a message, instead of only when receiving a Pong.

👍

> C) Disable the keep-alive mechanism entirely when compiling to WASM (do this in addition to A, since servers won't compile to WASM and still need the keep-alive mechanism).

👍 I'd skip sending Ping/Pong when in browser, I think it will be handled by the native browser API. Keep-alive is not that important after all.
We can provide some comments for users, that when they use WASM - the heartbeat configuration won't be used.
