### ISSUE TITLE
Reconnect attempt is delayed

### ISSUE THREAD

**Issue by UkoeHB** [gbaranski/ezsockets#78]
If a client wants to reconnect, it first [waits](https://github.com/gbaranski/ezsockets/blob/52c4b7898e537a1acb179503a89e5612ecd730f4/src/client.rs#L386) for a reconnect interval to pass. Is there a specific reason it needs to be this way? I'd rather try to reconnect immediately, then if that fails wait for the reconnect interval to pass.

It was moved to the start of the loop in [this commit](https://github.com/gbaranski/ezsockets/commit/ffd0a59dcea1ab93ec8d4fdd6c614b78cfec0f35) without explanation.

**Comment by gbaranski** [comment]
well, I thought it could be better to not reconnect that quickly because the server might be still down.
But actually yeah it makes sense to not wait the first interval.
