### ISSUE TITLE
Client in browser

### ISSUE THREAD

**Issue by UkoeHB** [gbaranski/ezsockets#79]
It would great if `ezsockets::Client` could be used in the browser. There are a few things blocking that scenario:

1. Ping/Pong are not supported in the browser.

See #76, #77.

2. `tokio` is not supported in the browser.

I wrote a crate [`enfync`](https://github.com/UkoeHB/enfync) that supports arbitrary async backends (including `tokio` and WASM).

3. `tokio-tungstenite` is not supported in the browser (can't do `tokio_tungstenite::connect()`).

There is a nice crate [`tokio-tungstenite-wasm`](https://github.com/TannerRogalsky/tokio-tungstenite-wasm) that provides a WASM client connector with a very similar interface to `tokio_tungstenite::connect()` (actually it uses `tokio-tungstenite` for the native backend, but we don't want that since his crate doesn't emit Ping/Pong messages).

I will write an experimental implementation using the above solutions, and follow up here.

**Comment by gbaranski** [comment]
Yep that's definitely useful.
AFAIK [WebSocket](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) is automatically sending Pong after Ping received.
So we can just not send the Ping's to Server when in browser.
