### ISSUE TITLE
Question: can this be used to send json files back and forth?

### ISSUE THREAD

**Issue by jhjacobs81** [gbaranski/ezsockets#9]
I’m very new to Rust (i just recently finished my Hello World program) but i am looking for a basic server/client system that can send JSON files back and forth for compliance checks of endpoints.

basicly the server will send the client a list of checks to perform (atm registry checks since thats what im learning) which the client performs and then sends back the results. The server will then store those results in a (postgresql) database where a web client then can grab the results and build piecharts of it. 

Something like that :)

**Comment by gbaranski** [comment]
Yes! You can use `serde_json` crate to encode & decode the data to String type, and with this you can easily send it over the socket.
